---
version: '1.0'
box: abs

name: cloudartifact

# pipeline -> stage -> tasks
vars:
  group.id: xyz.opstack.jenkins.tasks
  artifact.id: ${meta.name}

stages:
  - name: pkg
    tasks:
      - task.id: semver
      - task.id: opspkg
        artifact.id: ${meta.name}
        fileset.dir: ${ws.dir}
        fileset.includes: 'run.xml,convertor/*.*,macro/*.xml,tool/*,VERSION'

  - name: artifact
    tasks:
      - task.id: ftpartifact
        scm.type: git
        artifact.lane: jenkins
        fileset.dir: ${ws.dir}
        fileset.includes: ${meta.name}-*.tar.gz

pipelines:
  - name: dev
    stages:
      - pkg
      - artifact

default: dev
